language: bash
script:
- "true"
deploy:
  provider: script
  skip_cleanup: true
  script: curl -sSL https://raw.githubusercontent.com/Fryguy/travis-trigger-example/master/trigger.sh | bash -s
  on:
    branch: master
